[build]
rustflags = ["-Zthreads=14", "-Zshare-generics"]
incremental = true

[profile.dev]
opt-level = "z"
debug = 1
codegen-units = 1024
codegen-backend = "cranelift"

[unstable]
codegen-backend = true

[profile.release]
codegen-backend = "cranelift"
