#command_timeout = 3000
format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$directory\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$kubernetes\
${custom.kc-spark}\n\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$gleam\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
${custom.scala}\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$nats\
$direnv\
$env_var\
$crystal\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell\
$character"""

[kubernetes]
format = 'on [⛵ $context \($namespace\)](dimmed green) '
disabled = false

[kubernetes.context_aliases]
"dev.local.cluster.k8s" = "dev"

[custom.kc-spark]
command = "echo $CLUSTER_NAME"
when = ''' [[ $PWD = $KCSPARK && "$CLUSTER_NAME" != "" ]] '''
format = 'on  ⭐️ kc-spark \([$output]($style)\) '

[custom.scala]
command = "echo v$(sbt scalaVersion | tail -1 | awk '{print $2}')"
detect_extensions = ['sbt', 'scala']
detect_files = ['.scalaenv', '.sbtenv', 'build.sbt']
symbol = '🆂'
format = 'via [$symbol($output )](red) '

